// src/constants/mockData.ts
import type { Artwork } from "../types";

export const MOCK_ARTWORKS: Artwork[] = [
  {
    id: "mock-1",
    museumId: "met",
    externalId: "436532",
    title: "The Starry Night",
    artist: "Vincent van Gogh",
    year: 1889,
    description: "Oil on canvas",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1280px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg",
    additionalImages: [],
    aiKeywords: [],
    tags: ["landscape", "night", "stars", "post-impressionism"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    department: "European Paintings",
    culture: "Dutch",
    medium: "Oil on canvas",
    classification: "Paintings",
    isPublished: true,
  },
  {
    id: "mock-2",
    museumId: "met",
    externalId: "45434",
    title: "The Great Wave off Kanagawa",
    artist: "Katsushika Hokusai",
    year: 1831,
    description: "Polychrome woodblock print",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Tsunami_by_hokusai_19th_century.jpg/1280px-Tsunami_by_hokusai_19th_century.jpg",
    additionalImages: [],
    aiKeywords: [],
    tags: ["wave", "ocean", "ukiyo-e", "landscape"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    department: "Asian Art",
    culture: "Japanese",
    medium: "Polychrome woodblock print",
    classification: "Prints",
    isPublished: true,
  },
  {
    id: "mock-3",
    museumId: "met",
    externalId: "437893",
    title: "Girl with a Pearl Earring",
    artist: "Johannes Vermeer",
    year: 1665,
    description: "Oil on canvas",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/800px-1665_Girl_with_a_Pearl_Earring.jpg",
    additionalImages: [],
    aiKeywords: [],
    tags: ["portrait", "baroque", "dutch golden age"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    department: "European Paintings",
    culture: "Dutch",
    medium: "Oil on canvas",
    classification: "Paintings",
    isPublished: false,
  },
  {
    id: "mock-4",
    museumId: "met",
    externalId: "459010",
    title: "The Birth of Venus",
    artist: "Sandro Botticelli",
    year: 1485,
    description: "Tempera on canvas",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg/1280px-Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg",
    additionalImages: [],
    aiKeywords: [],
    tags: ["mythology", "renaissance", "venus"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    department: "European Paintings",
    culture: "Italian",
    medium: "Tempera on canvas",
    classification: "Paintings",
    isPublished: true,
  },
  {
    id: "mock-5",
    museumId: "met",
    externalId: "459189",
    title: "The Kiss",
    artist: "Gustav Klimt",
    year: 1908,
    description: "Oil and gold leaf on canvas",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg/800px-The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg",
    additionalImages: [],
    aiKeywords: [],
    tags: ["love", "art nouveau", "gold"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    department: "Modern Art",
    culture: "Austrian",
    medium: "Oil and gold leaf on canvas",
    classification: "Paintings",
    isPublished: false,
  },
  {
    id: "mock-6",
    museumId: "met",
    externalId: "459123",
    title: "A Sunday on La Grande Jatte",
    artist: "Georges Seurat",
    year: 1886,
    description: "Oil on canvas",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884-86.jpg/1280px-A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884-86.jpg",
    additionalImages: [],
    aiKeywords: [],
    tags: ["pointillism", "park", "impressionism"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    department: "Modern Art",
    culture: "French",
    medium: "Oil on canvas",
    classification: "Paintings",
    isPublished: true,
  },
];