/*
import { Artwork } from '../types';

export const MOCK_ARTWORKS: Artwork[] = [
  {
    id: '1',
    title: 'Starry Night',
    artist: 'Vincent van Gogh',
    date: '1889',
    medium: 'Oil on canvas',
    dimensions: '73.7 cm × 92.1 cm',
    department: 'Paintings',
    tags: ['post-impressionism', 'landscape', 'night'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1280px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/300px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg',
  },
  {
    id: '2',
    title: 'The Great Wave off Kanagawa',
    artist: 'Katsushika Hokusai',
    date: '1831',
    medium: 'Woodblock print',
    dimensions: '25.7 cm × 37.8 cm',
    department: 'Prints',
    culture: 'Japanese',
    tags: ['ukiyo-e', 'landscape', 'sea'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/The_Great_Wave_off_Kanagawa.jpg/1280px-The_Great_Wave_off_Kanagawa.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/The_Great_Wave_off_Kanagawa.jpg/300px-The_Great_Wave_off_Kanagawa.jpg',
  },
  {
    id: '3',
    title: 'Girl with a Pearl Earring',
    artist: 'Johannes Vermeer',
    date: '1665',
    medium: 'Oil on canvas',
    dimensions: '44.5 cm × 39 cm',
    department: 'Paintings',
    tags: ['baroque', 'portrait', 'dutch'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/1280px-1665_Girl_with_a_Pearl_Earring.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/300px-1665_Girl_with_a_Pearl_Earring.jpg',
  },
];

*/
import type { Artwork } from '../types';
export const MOCK_ARTWORKS: Artwork[] = [
  {
    objectID: 1,
    title: "The Starry Night",
    artistDisplayName: "Vincent van Gogh",
    objectDate: "1889",
    department: "European Paintings",
    medium: "Oil on canvas",
    primaryImage:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1280px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg",
    objectURL: "https://www.metmuseum.org/art/collection/search/436532",
    classification: "Paintings",
    culture: "Dutch",
    tags: ["landscape", "night", "stars", "post-impressionism"],
    isPublished: true,
  },
  {
    objectID: 2,
    title: "The Great Wave off Kanagawa",
    artistDisplayName: "Katsushika Hokusai",
    objectDate: "ca. 1830–32",
    department: "Asian Art",
    medium: "Polychrome woodblock print",
    primaryImage:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Tsunami_by_hokusai_19th_century.jpg/1280px-Tsunami_by_hokusai_19th_century.jpg",
    objectURL: "https://www.metmuseum.org/art/collection/search/45434",
    classification: "Prints",
    culture: "Japanese",
    tags: ["wave", "ocean", "ukiyo-e", "landscape"],
    isPublished: true,
  },
  {
    objectID: 3,
    title: "Girl with a Pearl Earring",
    artistDisplayName: "Johannes Vermeer",
    objectDate: "ca. 1665",
    department: "European Paintings",
    medium: "Oil on canvas",
    primaryImage:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/800px-1665_Girl_with_a_Pearl_Earring.jpg",
    objectURL: "https://www.metmuseum.org/art/collection/search/437893",
    classification: "Paintings",
    culture: "Dutch",
    tags: ["portrait", "baroque", "dutch golden age"],
    isPublished: false,
  },
  {
    objectID: 4,
    title: "The Birth of Venus",
    artistDisplayName: "Sandro Botticelli",
    objectDate: "ca. 1484–86",
    department: "European Paintings",
    medium: "Tempera on canvas",
    primaryImage:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg/1280px-Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg",
    objectURL: "https://www.metmuseum.org/art/collection/search/459010",
    classification: "Paintings",
    culture: "Italian",
    tags: ["mythology", "renaissance", "venus"],
    isPublished: true,
  },
  {
    objectID: 5,
    title: "The Kiss",
    artistDisplayName: "Gustav Klimt",
    objectDate: "1907–08",
    department: "Modern Art",
    medium: "Oil and gold leaf on canvas",
    primaryImage:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg/800px-The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg",
    objectURL: "https://www.metmuseum.org/art/collection/search/459189",
    classification: "Paintings",
    culture: "Austrian",
    tags: ["love", "art nouveau", "gold"],
    isPublished: false,
  },
  {
    objectID: 6,
    title: "A Sunday on La Grande Jatte",
    artistDisplayName: "Georges Seurat",
    objectDate: "1884–86",
    department: "European Paintings",
    medium: "Oil on canvas",
    primaryImage:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884-86.jpg/1280px-A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884-86.jpg",
    objectURL: "https://www.metmuseum.org/art/collection/search/459123",
    classification: "Paintings",
    culture: "French",
    tags: ["pointillism", "park", "impressionism"],
    isPublished: true,
  },
];

const AI_KEYWORD_POOL = [
  "atmospheric depth",
  "warm tonality",
  "chiaroscuro",
  "gestural marks",
  "negative space",
  "textural contrast",
  "chromatic harmony",
  "spatial tension",
  "rhythmic composition",
  "symbolic elements",
  "narrative layering",
  "optical illusion",
  "cultural motifs",
  "emotional resonance",
  "figurative abstraction",
  "material richness",
];
